ashimmu/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('eve_auth.urls', namespace='eve_auth')),
    path('', include('discord_auth.urls', namespace='discord')),
]

discord_auth/urls.py
from django.urls import path

import discord_auth.views


app_name = 'discord_auth'


urlpatterns = [
    path('', discord_auth.views.TokenView.as_view(), name='token'),
]

eve_auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

import eve_auth.views


app_name = 'eve_auth'


urlpatterns = [
    path('login/', eve_auth.views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('callback/', eve_auth.views.CallbackView.as_view(), name='callback'),
]

discord_auth/models.py
import random
import string

from django.contrib.auth.models import Group
from django.db import models
from django.conf import settings


def get_random_token():
    return ''.join(
        random.choice(string.ascii_letters + string.digits)
        for _ in range(DiscordAuthToken.TOKEN_LENGTH)
    )


class DiscordAuthToken(models.Model):
    TOKEN_LENGTH = 20

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        models.CASCADE,
        related_name='token',
        primary_key=True
    )

    token = models.CharField(
        max_length=TOKEN_LENGTH,
        default=get_random_token,
        db_index=True
    )


class DiscordUser(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        models.CASCADE,
        related_name='discord',
        primary_key=True
    )

    id = models.CharField(max_length=128, db_index=True, unique=True)


class DiscordRole(models.Model):
    id = models.CharField(max_length=128, primary_key=True)

    group = models.ManyToManyField(
        Group,
        related_name='discord_role',
        db_index=True,
    )

    name = models.CharField(max_length=128, db_index=True)


class AssignableRole(models.Model):
    name = models.CharField(max_length=64, primary_key=True)
    role = models.ForeignKey(DiscordRole, models.CASCADE)

eve_auth/models.py
import requests
import json
import esipy

from django.conf import settings
from django.db import models, transaction
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group


ESI_APP = esipy.App.create(url="https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility")
ESI_CLIENT = esipy.EsiClient(
    header={'User-Agent': 'Sharad Heft - Predditors Discord auth'},
)


class EveData(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='eve'
    )

    full_name = models.CharField(max_length=64)
    character_id = models.BigIntegerField()

    class Meta:
        verbose_name = 'EVE Data'
        verbose_name_plural = 'EVE Data'

    def update_groups(self):
        self.__update_affiliation_groups()

    def __update_affiliation_groups(self):
        corp, alliance = self.get_allegiance()

        with transaction.atomic():
            self.user.groups.remove(
                *self.user.groups.filter(
                    Q(name__startswith='corporation_') |
                    Q(name__startswith='alliance_')
                )
            )

            if alliance is not None:
                alliance, _ = Group.objects.get_or_create(name='alliance_%d' % alliance)
                self.user.groups.add(alliance)

            corporation, _ = Group.objects.get_or_create(name='corporation_%d' % corp)
            self.user.groups.add(corporation)

    def get_allegiance(self):
        data = ESI_CLIENT.request(
            ESI_APP.op['post_characters_affiliation'](
                characters=[self.character_id]
            )
        ).data[0]

        return data['corporation_id'], data.get('alliance_id', None)

    def __str__(self):
        return self.full_name

discord_auth/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.views import View
from django.shortcuts import render

from discord_auth.models import DiscordAuthToken


class TokenView(LoginRequiredMixin, View):
    def get(self, request):
        DiscordAuthToken.objects.filter(user=request.user).delete()

        return render(
            request,
            'discord_auth/token.html',
            {
                'token': DiscordAuthToken.objects.create(user=request.user),
            }
        )

eve_auth/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView, View
from django.conf import settings
from django.shortcuts import redirect

from esipy import EsiSecurity


class SecurityView(View):
    security = EsiSecurity(
        redirect_uri=settings.OAUTH_EVEONLINE_CALLBACK,
        client_id=settings.OAUTH_EVEONLINE_KEY,
        secret_key=settings.OAUTH_EVEONLINE_SECRET,
    )


class LoginView(SecurityView):
    def get(self, *args, **kwargs):
        return redirect(self.security.get_auth_uri())


class CallbackView(SecurityView):
    def get(self, request, *args, **kwargs):
        self.security.auth(request.GET['code'])

        user = authenticate(request, **self.security.verify())

        if user is not None:
            login(request, user)

        return redirect('/')

discord_auth/templates/discord_auth/token.html
{% extends 'base.html' %} {% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <img style="max-width: 100%" src="https://discordapp.com/assets/1c8a54f25d101bdc607cec7228247a9a.svg">
        </div>
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
            <h1>Discord</h1>
            <p class="lead">
                Below is your Discord authentication token. Enter the command
                into the lobby channel and you should receive the correct roles.
            </p>
            <kbd>!auth {{ token.token }}</kbd><br /><br />
            <p>
                Please be aware that this token will be invalidated when you
                refresh this page. This will not remove your existing roles.
            </p>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{{ ASHIMMU_SITE_NAME }}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://bootswatch.com/4/superhero/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <style>
      html {
        overflow-y:scroll;
      }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <div class="container">
        <span class="navbar-brand" href="#">{{ ASHIMMU_SITE_NAME }}</span>
        <ul class="navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li class="nav-item my-auto">
              <span class="nav-link p-0">
                <img src="https://image.eveonline.com/Character/{{ user.eve.character_id}}_32.jpg" />
                <span class="py-auto">{{ user.eve.full_name }}</span>
              </span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'eve_auth:logout' %}">
                Log out
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'social:begin' 'eveonline' %}">Log in</a>
            </li>
          {% endif %}
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %}
    </div>

    <main role="main" class="container">
      {% block content %} {% endblock %}
    </main>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
  </body>
</html>